### ISSUE TITLE
 to implement  fan control between reboots

### ISSUE THREAD

**Issue by plum** [juampapo546/Fan-control#12]
Could you suggest the most straightforward strategy to implement  desirable fan speeds  between roboots ,   i.e those found found after using fan-control? 

FOr example I find setting my fan spped to 1980 RPM  with the command 'fan hdd 20' most useful,  in order to tame it at relatively low temperatures of  around 30 degrees C.

THanks

**Comment by JuampiCarosi** [comment]
It's a good idea however it would take quite an extra work.
All the script does is sets the fan mode to controlled state (tells de os to look at the fan_speed file to actually set de file speed) and sets the file speed to the specific value.
For it to persist across reboots it would either need to be a daemon running that auto starts at reboot or to have the script run at boot from init.d  (or similar) with some default  (or configurable)  parameters.
Either way I cannot pursue the idea right now due to my limited free time between studies and work and my basic current knowledge in bash. However feel free to draft a PR and I will happily look over it.
PD: Some time ago I rewrote it in rust, it might be easier to go from there.

**Comment by JuampiCarosi** [comment]
If you are feeling lost, the easiest option without getting your hands dirty would be running the script at boot with the parameters you usually run the script.

**Comment by plum** [comment]
@JuampiCarosi  thnaks for kind reply Juampi. Yes I was going to run a script  triggered by login at tty., but I thought i'dpop the question to you first, to be certain about what I understand of tyou script. 

 Meanhwile I'll investigate why the existing fan curve for hd appears to be silly, and perhaps change that  in manual mode if I can, although  pwmconfig  doesnt  find a pwm control - in spite of listing them with sensorspdetect.  Perhaps I can do it entirely by hand.
 

- Imac 2011 27" i7 
-  arch-lts

**Comment by JuampiCarosi** [comment]
Yeah, tbh I never knew why the HDD fan behaves that way, I always thought it was because I had my drive removed and installed an SSD on its place and the sensor got borked in the process (that's actually why I wrote the script xd)

**Comment by plum** [comment]
@JuampiCarosi  

> Yeah, tbh I never knew why the HDD fan behaves that way, I always thought it was because I had my drive removed and installed an SSD on its place and the sensor got borked in the process (that's actually why I wrote the script xd)

Snap!  This machine had a SSD onstalled in place.  

BUt otherwise, it is rather excellent.
